
import { Lead, LeadStatus, KanbanColumn } from './types';

export const KANBAN_COLUMNS: KanbanColumn[] = [
    { id: LeadStatus.NEW, title: 'New' },
    { id: LeadStatus.CONTACTED, title: 'Contacted' },
    { id: LeadStatus.QUALIFIED, title: 'Qualified' },
    { id: LeadStatus.PROPOSAL, title: 'Proposal Sent' },
    { id: LeadStatus.WON, title: 'Closed Won' },
    { id: LeadStatus.LOST, title: 'Closed Lost' },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    name: 'John Doe',
    company: 'Acme Inc.',
    value: 5000,
    status: LeadStatus.NEW,
    contactedDate: '2023-10-01',
    followUpDate: '2023-10-15',
    assignedTo: 'Alice',
    avatar: 'https://picsum.photos/seed/lead-1/40/40',
  },
  {
    id: 'lead-2',
    name: 'Jane Smith',
    company: 'Globex Corp.',
    value: 12000,
    status: LeadStatus.CONTACTED,
    contactedDate: '2023-09-28',
    followUpDate: '2023-10-12',
    assignedTo: 'Bob',
    avatar: 'https://picsum.photos/seed/lead-2/40/40',
  },
  {
    id: 'lead-3',
    name: 'Peter Jones',
    company: 'Stark Industries',
    value: 7500,
    status: LeadStatus.QUALIFIED,
    contactedDate: '2023-09-25',
    followUpDate: '2023-10-10',
    assignedTo: 'Alice',
    avatar: 'https://picsum.photos/seed/lead-3/40/40',
  },
   {
    id: 'lead-4',
    name: 'Mary Williams',
    company: 'Wayne Enterprises',
    value: 25000,
    status: LeadStatus.PROPOSAL,
    contactedDate: '2023-09-20',
    assignedTo: 'Charlie',
    avatar: 'https://picsum.photos/seed/lead-4/40/40',
  },
  {
    id: 'lead-5',
    name: 'David Brown',
    company: 'Cyberdyne Systems',
    value: 15000,
    status: LeadStatus.WON,
    contactedDate: '2023-08-15',
    assignedTo: 'Bob',
    avatar: 'https://picsum.photos/seed/lead-5/40/40',
  },
    {
    id: 'lead-6',
    name: 'Susan Miller',
    company: 'Ollivanders',
    value: 3000,
    status: LeadStatus.LOST,
    contactedDate: '2023-09-18',
    assignedTo: 'Alice',
    avatar: 'https://picsum.photos/seed/lead-6/40/40',
  },
    {
    id: 'lead-7',
    name: 'Michael Clark',
    company: 'Buy n Large',
    value: 9000,
    status: LeadStatus.NEW,
    contactedDate: '2023-10-02',
    followUpDate: '2023-10-17',
    assignedTo: 'Charlie',
    avatar: 'https://picsum.photos/seed/lead-7/40/40',
  },
  {
    id: 'lead-8',
    name: 'Linda Martinez',
    company: 'Gekko & Co',
    value: 18000,
    status: LeadStatus.QUALIFIED,
    contactedDate: '2023-09-30',
    followUpDate: '2023-10-14',
    assignedTo: 'Bob',
    avatar: 'https://picsum.photos/seed/lead-8/40/40',
  },
];
